### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots-cloud#3]
It is pretty easy to introduce the dark mode in the CSS file:
```css
@media (prefers-color-scheme: dark) {
    body {
      color: white;
      background: #333;
    }
  }
```
